# Generated by Django 4.2 on 2023-04-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('number_of_shipment', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Погрузка',
                'verbose_name_plural': 'Погрузки',
            },
        ),
    ]
